CREATE TABLE IF NOT EXISTS applications
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_id     BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    status     VARCHAR(20)                             NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_applications PRIMARY KEY (id),
    CONSTRAINT uq_application_job_user UNIQUE (job_id, user_id),
    CONSTRAINT fk_application_job FOREIGN KEY (job_id) REFERENCES jobs (id),
    CONSTRAINT fk_application_user FOREIGN KEY (user_id) REFERENCES users (id)
);
