CREATE TABLE IF NOT EXISTS companies
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    user_id    BIGINT                                  NOT NULL,
    is_active  BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_companies PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS jobs
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type         SMALLINT,
    position     VARCHAR(255),
    description  VARCHAR(255),
    date         VARCHAR(255),
    start_time   VARCHAR(255),
    end_time     VARCHAR(255),
    daily_value  DOUBLE PRECISION,
    requirements VARCHAR(255),
    open         BOOLEAN,
    open_until   TIMESTAMP WITHOUT TIME ZONE,
    company_id   BIGINT                                  NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_jobs PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS permissions
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS role_permissions
(
    permission_id BIGINT NOT NULL,
    role_id       BIGINT NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (permission_id, role_id)
);

CREATE TABLE IF NOT EXISTS roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    email      VARCHAR(255),
    password   VARCHAR(255),
    status     SMALLINT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE companies
    ADD CONSTRAINT uc_companies_name UNIQUE (name);

ALTER TABLE companies
    ADD CONSTRAINT uc_companies_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE companies
    ADD CONSTRAINT FK_COMPANIES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE jobs
    ADD CONSTRAINT FK_JOBS_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_rolper_on_permission FOREIGN KEY (permission_id) REFERENCES permissions (id);

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_rolper_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user_entity FOREIGN KEY (user_id) REFERENCES users (id);